### PR TITLE
Fix openapi create method.

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by yoyo2k** [comment]
De ce imporţi json când e metoda in requests?

**Comment by feketemihai** [comment]
Pentru ca nu stie openapi...chiar apelezi sa iti dea json..tot nu iti da...tot din content trebuie sa il iei...vezi pe opeanpai.ro la companies...cel putin mie imi da eroare ca nu e de tip json daca il las din requests...

**Comment by yoyo2k** [comment]
Se întâmplă aleator sau sunt cazuri concrete? Să nu fie o bubă cu requests.

**Comment by feketemihai** [comment]
Mai..la mine se intampla la toti ce ii am in baza...

**Comment by yoyo2k** [comment]
Foarte ciudat că mie nu mi s-a întâmplat niciodată să crape

**Comment by feketemihai** [comment]
de pe openapi...sau de pe mfinante?

**Comment by yoyo2k** [comment]
Ce excepţie îţi dă?

**Comment by yoyo2k** [comment]
Aaa.. iar nu merge mfinante?

**Comment by feketemihai** [comment]
File "/opt/odoo/l10n-romania/l10n_ro_fiscal_validation/res_partner.py", line 197, in button_get_partner_data
    super(res_partner, self).button_get_partner_data()
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 397, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/l10n-romania/partner_create_by_vat/res_partner.py", line 146, in button_get_partner_data
    res = res.json()
AttributeError: 'Response' object has no attribute 'json'

**Comment by yoyo2k** [comment]
Ce versiune de requests ai?

**Comment by feketemihai** [comment]
cica 0.8.2...

**Comment by feketemihai** [comment]
stai sa fac upgrade...

**Comment by feketemihai** [comment]
Acum imi da pe amandoua:

'ascii' codec can't decode byte 0xc8 in position 61: ordinal not in range(128)

RO25613345, ro10149310, 

is state...sau la altii cu nrc unic pe companie...de aia am facut celalalt pr...sa fie si company, vat, nrc unice...

**Comment by yoyo2k** [comment]
Şi ca nu e metoda json în requests şi ascii codec ?

**Comment by feketemihai** [comment]
acuma merge cu json...ramane doar ascii pentru 0xc8...
cu requests 2.5.1

**Comment by yoyo2k** [comment]
Poţi pune excepţia cu ascii?

**Comment by feketemihai** [comment]
'ascii' codec can't decode byte 0xc8 in position 61: ordinal not in range(128)

si pe mfinante ...si trece la openapi la fel...e de la Timishoara...

**Comment by yoyo2k** [comment]
Excepţia e de la diacritice. Vreau să văd excepţia să-mi dau seama când e aruncată.

**Comment by feketemihai** [comment]
cand face title la res['state']...sau si in adresa daca are diacritice...

**Comment by yoyo2k** [comment]
PS: funcţia _check_vat_ro nu e folosită, ar trebui scoasă

**Comment by yoyo2k** [comment]
Excepţia se ridică în partea de openapi?

**Comment by feketemihai** [comment]
La amandoua....

2015-02-12 07:34:49,702 9739 INFO fbr requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): www.mfinante.ro
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/**init**.py", line 846, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/**init**.py", line 723, in format
    return fmt.format(record)
  File "/opt/odoo/odoo/openerp/netsvc.py", line 124, in format
    return DBFormatter.format(self, record)
  File "/opt/odoo/odoo/openerp/netsvc.py", line 118, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/**init**.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 61: ordinal not in range(128)
Logged from file sql_db.py, line 241
2015-02-12 07:34:50,221 9739 INFO fbr requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): openapi.ro
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/**init**.py", line 846, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/**init**.py", line 723, in format
    return fmt.format(record)
  File "/opt/odoo/odoo/openerp/netsvc.py", line 124, in format
    return DBFormatter.format(self, record)
  File "/opt/odoo/odoo/openerp/netsvc.py", line 118, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/**init**.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 107: ordinal not in range(128)
Logged from file sql_db.py, line 241
2015-02-12 07:34:50,602 9739 ERROR fbr openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 393, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 397, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/l10n-romania/l10n_ro_fiscal_validation/res_partner.py", line 197, in button_get_partner_data
    super(res_partner, self).button_get_partner_data()
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 397, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/l10n-romania/partner_create_by_vat/res_partner.py", line 150, in button_get_partner_data
    [('name', '=', res['state'].title())])
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 1637, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 4605, in _search
    cr.execute(query_str, where_clause_params)
  File "/opt/odoo/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

**Comment by yoyo2k** [comment]
sigur e o problema de codare a textului (!= utf-8) - la mine tot e utf-8 (db, locale, etc)
1. http://docs.python-requests.org/en/latest/user/advanced/#encodings
   zice ca se poate rezolva setand Response.encoding manual
2. https://github.com/kennethreitz/requests/blob/master/requests/models.py (def json..)
   scrie despre JSON RFC si cum trebuie codate datele

**Comment by feketemihai** [comment]
ciudat e ca e utf-8...

**Comment by yoyo2k** [comment]
Encoding sau apparent_encoding sau amândouă.

Oricum, foarte ciudat că mie nu-mi dă nici o eroare. 

Apropo, dacă nu e nrc şi e authorization_number băgăm a_n?

**Comment by feketemihai** [comment]
nu...nu cred ca ar trebui sa le combinam...

**Comment by yoyo2k** [comment]
tot da aiureli?

**Comment by feketemihai** [comment]
cel putin la cei doi care i-am descoperit da...cu tot cu encoding...utf-8...pare ciudat de tot...si ma mir de ce si de pe finante nu ia cum trebuie...

**Comment by yoyo2k** [comment]
partea ciudata e ca la mine merge si mfin si openapi

**Comment by feketemihai** [comment]
pe cei 2 care i-am dat?

**Comment by yoyo2k** [comment]
da

**Comment by yoyo2k** [comment]
cu asta?

**Comment by feketemihai** [comment]
Asta il mai lasam deschis..pana ce mai am timp sa ma uit ce nu pusca la mine...

**Comment by yoyo2k** [comment]
iti merge?

**Comment by feketemihai** [comment]
nu am mai vazut erori...daca mai vad o sa-l deschid iar...

**Pull request closed without merging**
