### PR TITLE
Fix supplier invoice number in purchase journal.

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by cbssolutions** [comment]
La mine rezolva eroarea din registrul de cumparari
QWebException: "number" while evaluating
"inv1['number']"

**Comment by feketemihai** [comment]
@yoyo2k @dhongu @alexteodor ???

**Comment by cbssolutions** [comment]
Ok. Merge

**Comment by yoyo2k** [comment]
E ok

**Pull request merged**
